rooms:
  - capacity: 20
    name: Beamer Raum
  - capacity: 10
    name: Kleiner Raum
  - capacity: 5
    name: Couch
    fulfilled_room_constraints: ["gemütlich"]
timeslots:
  - name: Fr 10:30-12:30
    fulfilled_time_constraints: ["freitag"]
  - name: Fr 12:30-14:30
    fulfilled_time_constraints: ["freitag"]
  - name: Fr 15:30-17:30
    fulfilled_time_constraints: ["freitag"]
  - name: Fr 18:00-20:00
    fulfilled_time_constraints: ["freitag"]
  - name: Sa 10:30-12:30
    fulfilled_time_constraints: ["samstag"]
  - name: Sa 13:00-15:00
    fulfilled_time_constraints: ["samstag"]
  - name: Sa 15:00-17:00
    fulfilled_time_constraints: ["samstag"]
  - name: Sa 17:00-19:00
    fulfilled_time_constraints: ["samstag"]
  - name: So 10:30-12:30
    fulfilled_time_constraints: ["sonntag"]
